# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:14.17.6-alpine3.13

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/
    - .yarn

stages:
    - test
 
run-unit-test:
    stage: test
    script:
        - yarn install --cache-folder .yarn
        - yarn test
        # - npm install # Install all dependencies
        # - npm test # Test 
    only:
        - merge_requests